exports.help = require('./help')
exports.menusimple = require('./help2')
exports.info1 = require('./info1')
exports.donasi = require('./donasi')
exports.sewabot = require('./sewabot')
exports.hentong = require('./hentong')
